// DO NOT DELETE - TeamId index referral chart below
// const teamIndexChart = {
//     1: 'Arizona Cardinals',
//     2: 'Atlana Falcons',
//     3: 'Baltimore Ravens',
//     4: 'Buffalo Bills',
//     5: 'Carolina Panthers',
//     6: 'Chicago Bears',
//     7: 'Cincinnati Bengals',
//     8: 'Cleveland Browns',
//     9: 'Dallas Cowboys',
//     10: 'Denver Broncos',
//     11: 'Detroit Lions',
//     12: 'Green Bay Packers',
//     13: 'Houston Texans',
//     14: 'Indianapolis Colts',
//     15: 'Jacksonville Jaguars',
//     16: 'Kansas City Chiefs',
//     // 17: '',
//     // 18: '',
//     19: 'Miami Dolphins',
//     20: 'Minnesota Vikings',
//     21: 'New England Patriots',
//     22: 'New Orleans Saints',
//     23: 'New York Giants',
//     24: 'New York Jets',
//     25: 'Oakland Raiders',
//     26: 'Philadelphia Eagles',
//     // 27: '',
//     28: 'Pittsburg Steelers',
//     29: 'Los Angeles Chargers',
//     30: 'Seattle Seahawks',
//     31: 'San Francisco 49ers',
//     32: 'Los Angeles Rams',
//     33: 'Tampa Bay Buccaneers',
//     34: 'Tennessee Titans',
//     35: 'Washington Redskins',
// }

// const teamNameChart = [
//     'Arizona Cardinals',
//     'Atlana Falcons',
//     'Baltimore Ravens',
//     'Buffalo Bills',
//     'Carolina Panthers',
//     'Chicago Bears',
//     'Cincinnati Bengals',
//     'Cleveland Browns',
//     'Dallas Cowboys',
//     'Denver Broncos',
//     'Detroit Lions',
//     'Green Bay Packers',
//     'Houston Texans',
//     'Indianapolis Colts',
//     'Jacksonville Jaguars',
//     'Kansas City Chiefs',
//     'Miami Dolphins',
//     'Minnesota Vikings',
//     'New England Patriots',
//     'New Orleans Saints',
//     'New York Giants',
//     'New York Jets',
//     'Oakland Raiders',
//     'Philadelphia Eagles',
//     'Pittsburg Steelers',
//     'Los Angeles Chargers',
//     'Seattle Seahawks',
//     'San Francisco 49ers',
//     'Los Angeles Rams',
//     'Tampa Bay Buccaneers',
//     'Tennessee Titans',
//     'Washington Redskins',
// ]
