// DO NOT DELETE - TeamId index referral chart below
// const teamIndexChart = {
//     1: 'Arizona Cardinals',
//     2: 'Atlana Falcons',
//     3: 'Baltimore Ravens',
//     4: 'Buffalo Bills',
//     5: 'Carolina Panthers',
//     6: 'Chicago Bears',
//     7: 'Cincinnati Bengals',
//     8: 'Cleveland Browns',
//     9: 'Dallas Cowboys',
//     10: 'Denver Broncos',
//     11: 'Detroit Lions',
//     12: 'Green Bay Packers',
//     13: 'Houston Texans',
//     14: 'Indianapolis Colts',
//     15: 'Jacksonville Jaguars',
//     16: 'Kansas City Chiefs',
//     // 17: '',
//     // 18: '',
//     19: 'Miami Dolphins',
//     20: 'Minnesota Vikings',
//     21: 'New England Patriots',
//     22: 'New Orleans Saints',
//     23: 'New York Giants',
//     24: 'New York Jets',
//     25: 'Oakland Raiders',
//     26: 'Philadelphia Eagles',
//     // 27: '',
//     28: 'Pittsburg Steelers',
//     29: 'Los Angeles Chargers',
//     30: 'Seattle Seahawks',
//     31: 'San Francisco 49ers',
//     32: 'Los Angeles Rams',
//     33: 'Tampa Bay Buccaneers',
//     34: 'Tennessee Titans',
//     35: 'Washington Redskins',
// }

// const teamNameChart = [
//     'Arizona Cardinals',
//     'Atlana Falcons',
//     'Baltimore Ravens',
//     'Buffalo Bills',
//     'Carolina Panthers',
//     'Chicago Bears',
//     'Cincinnati Bengals',
//     'Cleveland Browns',
//     'Dallas Cowboys',
//     'Denver Broncos',
//     'Detroit Lions',
//     'Green Bay Packers',
//     'Houston Texans',
//     'Indianapolis Colts',
//     'Jacksonville Jaguars',
//     'Kansas City Chiefs',
//     'Miami Dolphins',
//     'Minnesota Vikings',
//     'New England Patriots',
//     'New Orleans Saints',
//     'New York Giants',
//     'New York Jets',
//     'Oakland Raiders',
//     'Philadelphia Eagles',
//     'Pittsburg Steelers',
//     'Los Angeles Chargers',
//     'Seattle Seahawks',
//     'San Francisco 49ers',
//     'Los Angeles Rams',
//     'Tampa Bay Buccaneers',
//     'Tennessee Titans',
//     'Washington Redskins',
// ]


// const teamsObjects = [
//     {teamId: 1, teamName: 'Arizona Cardinals', divsion: 'west', conference: 'nfc'},
//     {teamId: 2, teamName: 'Atlana Falcons', divsion: 'south', conference: 'nfc'},
//     {teamId: 3, teamName: 'Baltimore Ravens', divsion: 'north', conference: 'afc'},
//     {teamId: 4, teamName: 'Buffalo Bills', divsion: 'east', conference: 'afc'},
//     {teamId: 5, teamName: 'Carolina Panthers', divsion: 'south', conference: 'nfc'},
//     {teamId: 6, teamName: 'Chicago Bears', divsion: 'north', conference: 'nfc'},
//     {teamId: 7, teamName: 'Cincinnati Bengals', divsion: 'north', conference: 'afc'},
//     {teamId: 8, teamName: 'Cleveland Browns', divsion: 'north', conference: 'afc'},
//     {teamId: 9, teamName: 'Dallas Cowboys', divsion: 'east', conference: 'nfc'},
//     {teamId: 10, teamName: 'Denver Broncos', divsion: 'west', conference: 'afc'},
//     {teamId: 11, teamName: 'Detroit Lions', divsion: 'north', conference: 'nfc'},
//     {teamId: 12, teamName: 'Green Bay Packers', divsion: 'north', conference: 'nfc'},
//     {teamId: 13, teamName: 'Houston Texans', divsion: 'south', conference: 'afc'},
//     {teamId: 14, teamName: 'Indianapolis Colts', divsion: 'south', conference: 'afc'},
//     {teamId: 15, teamName: 'Jacksonville Jaguars', divsion: 'south', conference: 'afc'},
//     {teamId: 16, teamName: 'Kansas City Chiefs', divsion: 'west', conference: 'nfc'},
//     {teamId: 19, teamName: 'Miami Dolphins', divsion: 'east', conference: 'afc'},
//     {teamId: 20, teamName: 'Minnesota Vikings', divsion: 'north', conference: 'nfc'},
//     {teamId: 21, teamName: 'New England Patriots', divsion: 'east', conference: 'afc'},
//     {teamId: 22, teamName: 'New Orleans Saints', divsion: 'south', conference: 'nfc'},
//     {teamId: 23, teamName: 'New York Giants', divsion: 'east', conference: 'nfc'},
//     {teamId: 24, teamName: 'New York Jets', divsion: 'east', conference: 'afc'},
//     {teamId: 25, teamName: 'Oakland Raiders', divsion: 'west', conference: 'afc'},
//     {teamId: 26, teamName: 'Philadelphia Eagles', divsion: 'east', conference: 'nfc'},
//     {teamId: 28, teamName: 'Pittsburg Steelers', divsion: 'north', conference: 'afc'},
//     {teamId: 29, teamName: 'Los Angeles Chargers', divsion: 'west', conference: 'afc'},
//     {teamId: 30, teamName: 'Seattle Seahawks', divsion: 'west', conference: 'nfc'},
//     {teamId: 31, teamName: 'San Francisco 49ers', divsion: 'west', conference: 'nfc'},
//     {teamId: 32, teamName: 'Los Angeles Rams', divsion: 'west', conference: 'nfc'},
//     {teamId: 33, teamName: 'Tampa Bay Buccaneers', divsion: 'south', conference: 'nfc'},
//     {teamId: 34, teamName: 'Tennessee Titans', divsion: 'south', conference: 'afc'},
//     {teamId: 35, teamName: 'Washington Redskins', divsion: 'east', conference: 'nfc'},
// ]